---
galaxy_info:
  role_name: palimpsest
  author: openstack-afterglow
  description: Palimpsest Hub layer repository service deployment role for kolla-ansible
  min_ansible_version: "2.14"

dependencies: []
